version: '3'
services:
  db:
    image: postgres:14.4-alpine
    ports:
      - "5432:5432"
    container_name: db
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
  
  adminer2:
    container_name: adminer2
    hostname: adminer2
    image: adminer:4.7.5
    ports:
      - 8080:8080
    depends_on:
      - db
